name: satsails_wallet
description: "Sail your wealth to the cloud!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  local_auth: ^2.1.8
  animate_gradient: ^0.0.2+1
  web_socket_channel: ^2.4.0
  http: ^1.2.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  webview_flutter: ^4.5.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  btc_address_validate_swan: ^1.2.1
  fl_chart: ^0.66.2
  month_picker_dialog: ^2.11.0
  ffi: ^2.0.2
  ffigen: ^8.0.2
  freezed_annotation: ^2.4.1
  freezed: ^2.4.1
  nanoid: ^1.0.0
  logger: ^1.4.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_riverpod: ^2.5.1
  rxdart: ^0.27.7

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - lib/assets/SatSails.png
    - lib/assets/SatSailsWhite.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/SatSails.png"

ffigen:
  output: "lib/ffi/generated_bindings.dart"
  headers:
    entry-points:
      - "crypto/gdk-iphone/include/gdk/gdk.h"
      - "rust-elements-wrapper/bindings.h"
  typedefs:
    include:
      - ".*"
  functions:
    expose-typedefs:
      include:
        - ".*"
  symbol-address:
    include:
      - ".*"
  structs:
    exclude:
      - "(.*)sigaction(.*)"
  unions:
    exclude:
      - "(.*)sigaction(.*)"
  llvm-path:
    - "/opt/local/libexec/llvm-10"
    - "/Library/Developer/CommandLineTools/usr"