name: satsails
description: "Sail your wealth to the cloud!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  http: ^1.2.1
  local_auth: ^2.1.8
  web_socket_channel: ^2.4.0
  hive: ^2.2.3
  webview_flutter: ^4.5.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  fl_chart: ^0.66.2
  month_picker_dialog: ^2.11.0
  bip39: ^1.0.6
  flutter_riverpod: ^2.5.1
  bdk_flutter: ^0.31.1-dev
  flutter_i18n: ^0.35.1
  boltz_dart:
    git:
      url: https://github.com/SatoshiPortal/boltz-dart.git
      ref: trunk
  lwk_dart:
    git:
      url: https://github.com/SatoshiPortal/lwk-dart
      ref: trunk
  forex_currency_conversion: ^0.9.1
  icons_plus: ^5.0.0
  loading_animation_widget: ^1.2.1
  group_button: ^5.3.4
  pull_to_refresh: ^2.0.0
  responsive_framework: ^1.4.0
  liquid_pull_to_refresh: ^3.0.1
  bolt11_decoder: ^1.0.2
  action_slider: ^0.7.0
  hooks_riverpod: ^2.5.1
  interactive_slider: ^0.2.1
  currency_text_input_formatter: ^2.2.1
  fluttertoast: ^8.2.5
  flutter_card_swiper: ^7.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - lib/assets/satsails.png

flutter_launcher_icons:
  android: true
  image_path: "lib/assets/satsails.png"