name: satsails_wallet
description: "Sail your wealth to the cloud!"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  pin_code_fields: ^8.0.1
  local_auth: ^2.1.8
  animate_gradient: ^0.0.2+1
  web_socket_channel: ^2.4.0
  http: ^1.2.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - lib/assets/SatSails.png
    - lib/assets/SatSailsWhite.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/SatSails.png"